### ISSUE TITLE
Unable to install latest version of the automation toolchain via f5-cli

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/f5-cli#15]
Seems like the F5-CLI does not include the latest version of the ATC components in the list of valid versions.

Install code:
```bash
export as3_version=3.22.0
export do_version=1.15.0
export ts_version=1.14.0
export fast_version=1.3.0

for i in {6..7} 
do
    # authenticate to the BIG-IP
    docker exec -it f5-cli f5 login --authentication-provider bigip --host 10.1.1.$i --user admin --password $bigip_pwd

    # install the do, as3 and ts extensions
    docker exec -it f5-cli f5 bigip extension do install --version $do_version
    docker exec -it f5-cli f5 bigip extension as3 install --version $as3_version
    docker exec -it f5-cli f5 bigip extension ts install --version $ts_version
done
```

Error for DO:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/f5", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/__init__.py", line 108, in command_do
    package_url
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/extension_operations.py", line 105, in __init__
    self._extension_client = self._extension_client_attr(self._mgmt_client, **component_kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_do.py", line 49, in __init__
    use_latest_metadata=kwargs.pop('use_latest_metadata', False)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 68, in __init__
    version or self.get_latest_version()
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 157, in _validate_component_version
    'Valid component version must be provided: %s' % (versions)
f5sdk.exceptions.InvalidComponentVersionError: Valid component version must be provided: ['1.14.0', '1.13.0', '1.12.0', '1.11.1', '1.11.0', '1.10.0', '1.9.0', '1.8.0', '1.7.0', '1.6.0', '1.5.0', '1.4.0', '1.3.0', '1.2.0', '1.1.0']
```

Error for AS3:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/f5", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/__init__.py", line 69, in command_as3
    package_url)
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/extension_operations.py", line 105, in __init__
    self._extension_client = self._extension_client_attr(self._mgmt_client, **component_kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_as3.py", line 49, in __init__
    use_latest_metadata=kwargs.pop('use_latest_metadata', False)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 68, in __init__
    version or self.get_latest_version()
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 157, in _validate_component_version
    'Valid component version must be provided: %s' % (versions)
f5sdk.exceptions.InvalidComponentVersionError: Valid component version must be provided: ['3.21.0', '3.20.0', '3.19.1', '3.19.0', '3.18.0', '3.17.1', '3.17.0', '3.16.0', '3.15.1', '3.14.1', '3.15.0', '3.13.2', '3.14.0', '3.13.1', '3.13.0', '3.12.0', '3.11.0', '3.10.0', '3.9.0', '3.8.1', '3.8.0', '3.7.0', '3.5.1', '3.6.0', '3.5.0', '3.4.0', '3.3.0', '3.2.0', '3.1.0', '3.0.0']
```

Error for TS:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/f5", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/__init__.py", line 148, in command_ts
    package_url
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/extension_operations.py", line 105, in __init__
    self._extension_client = self._extension_client_attr(self._mgmt_client, **component_kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_ts.py", line 49, in __init__
    use_latest_metadata=kwargs.pop('use_latest_metadata', False)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 68, in __init__
    version or self.get_latest_version()
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 157, in _validate_component_version
    'Valid component version must be provided: %s' % (versions)
f5sdk.exceptions.InvalidComponentVersionError: Valid component version must be provided: ['1.13.0', '1.12.0', '1.11.0', '1.10.0', '1.9.0', '1.8.0', '1.7.0', '1.6.0', '1.5.0', '1.4.0', '1.3.0', '1.2.0', '1.1.0']
```

**Comment by codygreen** [comment]
I tried to install the latest AS3 release from last night, [3.22.1](https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.22.1), and I receive the same error:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/f5", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/__init__.py", line 69, in command_as3
    package_url)
  File "/usr/local/lib/python3.7/site-packages/f5cli/commands/cmd_bigip/extension_operations.py", line 105, in __init__
    self._extension_client = self._extension_client_attr(self._mgmt_client, **component_kwargs)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_as3.py", line 49, in __init__
    use_latest_metadata=kwargs.pop('use_latest_metadata', False)
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 68, in __init__
    version or self.get_latest_version()
  File "/usr/local/lib/python3.7/site-packages/f5sdk/bigip/extension/extension_metadata.py", line 157, in _validate_component_version
    'Valid component version must be provided: %s' % (versions)
f5sdk.exceptions.InvalidComponentVersionError: Valid component version must be provided: ['3.21.0', '3.20.0', '3.19.1', '3.19.0', '3.18.0', '3.17.1', '3.17.0', '3.16.0', '3.15.1', '3.14.1', '3.15.0', '3.13.2', '3.14.0', '3.13.1', '3.13.0', '3.12.0', '3.11.0', '3.10.0', '3.9.0', '3.8.1', '3.8.0', '3.7.0', '3.5.1', '3.6.0', '3.5.0', '3.4.0', '3.3.0', '3.2.0', '3.1.0', '3.0.0']```

**Comment by codygreen** [comment]
I've confirmed this issue is specific to the f5-cli and not the f5-sdk-python. I can install AS3 3.22.0 via f5-sdk-python.

The F5-cli does not see latest version of AS3:
```bash
docker exec -it f5-cli f5 bigip extension as3 list-versions
2020-09-09 14:32:38,822 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
2020-09-09 14:32:38,997 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
2020-09-09 14:32:39,095 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
2020-09-09 14:32:39,161 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
2020-09-09 14:32:39,219 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
[
    "3.21.0",
    "3.20.0",
    "3.19.1",
    "3.19.0",
    "3.18.0",
    "3.17.1",
    "3.17.0",
    "3.16.0",
    "3.15.1",
    "3.14.1",
    "3.15.0",
    "3.13.2",
    "3.14.0",
    "3.13.1",
    "3.13.0",
    "3.12.0",
    "3.11.0",
    "3.10.0",
    "3.9.0",
    "3.8.1",
    "3.8.0",
    "3.7.0",
    "3.5.1",
    "3.6.0",
    "3.5.0",
    "3.4.0",
    "3.3.0",
    "3.2.0",
    "3.1.0",
    "3.0.0"
]
```
```bash
docker images f5devcentral/f5-cli
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
f5devcentral/f5-cli   latest              58141cc49608        4 months ago        564MB
```

**Comment by nmenant** [comment]
Thanks Cody, i've added AUTOSDK-447 to our backlog
