### ISSUE TITLE
Yaml error when running "f5 login"

### ISSUE THREAD

**Issue by dstokesf5** [f5devcentral/f5-cli#17]
I have a script that is running f5 login:

```bash
f5 login \
    --authentication-provider bigip \
    --host $AS3_IP \
    --port $AS3_PORT \
    --user $AS3_USERNAME \
    --password $AS3_PASSWORD
```

I have confirmed that the environment variables are correct, and this used to work for me. However, recently I have been getting this stack trace when trying to run `f5 login`:
```
2021-02-18 10:54:17,725 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
2021-02-18 10:54:18,280 - f5sdk.utils.http_utils - WARNING: SSL Insecure request, recommend adding a valid certificate to the device
Traceback (most recent call last):
  File "/home/dstokes/share/f5-appsvcs/venv/bin/f5", line 8, in <module>
    sys.exit(cli())
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/f5cli/commands/cmd_login/__init__.py", line 113, in cli
    auth_client.store_auth('create')
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/f5cli/config/auth.py", line 176, in store_auth
    auth_contents = self._load_auth_contents()
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/f5cli/config/auth.py", line 86, in _load_auth_contents
    auth_contents = yaml.safe_load(file)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/dstokes/share/f5-appsvcs/venv/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/home/dstokes/.f5_cli/auth.yaml", line 8, column 1
could not find expected ':'
  in "/home/dstokes/.f5_cli/auth.yaml", line 9, column 1
```

I am using Python 3.9.1. My gut tells me this is related to some kind of versioning issue, so below is the output from pip list:
```
Package                       Version
----------------------------- -------------------------
alabaster                     0.7.12
awscli                        1.19.10
Babel                         2.9.0
bcrypt                        3.2.0
botocore                      1.20.10
certifi                       2020.12.5
cffi                          1.14.5
chardet                       4.0.0
click                         7.1.2
click-repl                    0.1.6
cloud-sptheme                 1.10.1.post20200504175005
colorama                      0.4.3
commonmark                    0.9.1
cryptography                  3.4.6
decorator                     4.4.2
docutils                      0.15.2
f5-cli                        0.9.2
f5-sdk-python                 0.9.2
f5-sphinx-theme               2.0.7
f5-teem                       1.0.2
idna                          2.10
imagesize                     1.2.0
Jinja2                        2.11.3
jmespath                      0.10.0
MarkupSafe                    1.1.1
packaging                     20.9
paramiko                      2.7.2
pip                           20.3.3
prompt-toolkit                3.0.16
py                            1.10.0
pyasn1                        0.4.8
pycparser                     2.20
Pygments                      2.8.0
PyNaCl                        1.4.0
pyparsing                     2.4.7
python-dateutil               2.8.1
pytz                          2021.1
PyYAML                        5.3.1
recommonmark                  0.7.1
requests                      2.25.1
retry                         0.9.2
rsa                           4.5
s3transfer                    0.3.4
setuptools                    51.3.3
six                           1.15.0
snowballstemmer               2.1.0
Sphinx                        1.8.5
sphinx-copybutton             0.3.1
sphinxcontrib-serializinghtml 1.1.4
sphinxcontrib-websupport      1.2.4
sphinxjp.themes.basicstrap    0.5.0
urllib3                       1.26.3
wcwidth                       0.2.5
wheel                         0.36.2
```

**Comment by dstokesf5** [comment]
This was caused by `~/.f5_cli/auth.yaml` becoming corrupt. Deleting the file got me around the issue.
